### ISSUE TITLE
Uninstall problem

### ISSUE THREAD

**Issue by fact0real** [ether/ep_right_to_left#4]
Hi all,
After I have uninstalled this plugin, my Etherpad is Right To Left, and I can't change the defulat setting to LTR.
Please verify and solve this issue.
Regards

**Comment by JohnMcLear** [comment]
If you clear cookies does the problem persist?  Afaik it works by toggling the default to RTL

**Comment by fact0real** [comment]
You are right, I cleared my cache and problem solved.
Thanks

**Comment by JohnMcLear** [comment]
That's the correct behaviour.  If you changed it back from right to left to left to right the new cookie setting would persist.
